### ISSUE TITLE
AttributeError: 'module' object has no attribute 'SSLContext'

### ISSUE THREAD

**Issue by crastinatorpro** [SteveMcGrath/pySecurityCenter#13]
SC4
Python 2.6.6
pySecurityCenter-2.1.7

Receiving the following module object errors:

# python runcsv.py
Traceback (most recent call last):
  File "runcsv.py", line 30, in <module>
    port=conf.getint('Settings', 'port'))
  File "build/bdist.linux-x86_64/egg/securitycenter/sc4.py", line 112, in __init__
  File "build/bdist.linux-x86_64/egg/securitycenter/sc4.py", line 920, in _system
  File "build/bdist.linux-x86_64/egg/securitycenter/sc4.py", line 338, in raw_query
  File "build/bdist.linux-x86_64/egg/securitycenter/sc4.py", line 296, in _request
AttributeError: 'module' object has no attribute 'SSLContext'

# python example.py 
Traceback (most recent call last):
  File "example.py", line 11, in <module>
    sc = securitycenter.SecurityCenter(host, username, password)
  File "build/bdist.linux-x86_64/egg/securitycenter/sc4.py", line 112, in __init__
  File "build/bdist.linux-x86_64/egg/securitycenter/sc4.py", line 920, in _system
  File "build/bdist.linux-x86_64/egg/securitycenter/sc4.py", line 338, in raw_query
  File "build/bdist.linux-x86_64/egg/securitycenter/sc4.py", line 296, in _request
AttributeError: 'module' object has no attribute 'SSLContext'

# python dns_populate.py
Traceback (most recent call last):
  File "dns_populate.py", line 28, in <module>
    sc = SecurityCenter(host, username, password)
  File "build/bdist.linux-x86_64/egg/securitycenter/sc4.py", line 112, in __init__
  File "build/bdist.linux-x86_64/egg/securitycenter/sc4.py", line 920, in _system
  File "build/bdist.linux-x86_64/egg/securitycenter/sc4.py", line 338, in raw_query
  File "build/bdist.linux-x86_64/egg/securitycenter/sc4.py", line 296, in _request
AttributeError: 'module' object has no attribute 'SSLContext'

**Comment by SteveMcGrath** [comment]
Can you please give me the output of the following code?

````python
import ssl
protocol = ssl.PROTOCOL_TLSv1
print ssl.SSLContext(protocol)
````

**Comment by crastinatorpro** [comment]
>>> import ssl
>>> protocol = ssl.PROTOCOL_TLSv1
>>> print ssl.SSLContext(protocol)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'SSLContext'

**Comment by SteveMcGrath** [comment]
Can you remove `, context=ssl.SSLContext(ssl.PROTOCOL_TLSv1)` from Line 288 in sc4.py and let me know if that resolved the issue?

**Comment by crastinatorpro** [comment]
My line number was 297.  Regardless after editing the line to `resp = urlopen(Request(self._url, payload, headers)` I now get a error at the following line 298.  The error is as follows:

Traceback (most recent call last):
  File "runcsv.py", line 20, in <module>
    from securitycenter import SecurityCenter
  File "build/bdist.linux-x86_64/egg/securitycenter/__init__.py", line 1, in <module>
    #
  File "/usr/lib/python2.6/site-packages/pySecurityCenter-2.1.7-py2.6.egg/securitycenter/sc4.py", line 298
    data = resp.read()
       ^
SyntaxError: invalid syntax

**Comment by crastinatorpro** [comment]
As I am running CentOS 6 it defaults to python 2.6.6.  Supposedly SSLContext was introduced in python 2.7.9.  I managed to fix my issue by downloading and doing a make altinstall of python2.7.  I then reran the pySecurityCenter setup using python2.7.  And naturally, evert time I run a pySecurityCenter script I call it using python2.7.

**Comment by SteveMcGrath** [comment]
so I added code to check for the versions.  please try 2.1.8 and let me know how that operates on 2.6.6.  I'm currently waiting to switch over to a centos 6 vm to test...
