### ISSUE TITLE
Issues installing

### ISSUE THREAD

**Issue by cstewart87** [SteveMcGrath/pySecurityCenter#14]
I receive the following error when attempting to install this library.  The biggest issue that stands out to me is the last line (**`ImportError: No module named requests.packages.urllib3.exceptions`**)

Any thoughts on how to proceed forward with this error?

```
STDOUT: Downloading/unpacking pysecuritycenter==2.1
  Downloading pySecurityCenter-2.1.tar.gz
  Running setup.py (path:/tmp/pip-build-Wfk05K/pysecuritycenter/setup.py) egg_info for package pysecuritycenter
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-Wfk05K/pysecuritycenter/setup.py", line 3, in <module>
 import securitycenter
      File "securitycenter/__init__.py", line 1, in <module>
 from base import SecurityCenter4 as SecurityCenter
      File "securitycenter/base.py", line 1, in <module>
 from requests.packages.urllib3.exceptions import InsecureRequestWarning
    ImportError: No module named requests.packages.urllib3.exceptions
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-Wfk05K/pysecuritycenter/setup.py", line 3, in <module>

    import securitycenter

  File "securitycenter/__init__.py", line 1, in <module>

    from base import SecurityCenter4 as SecurityCenter

  File "securitycenter/base.py", line 1, in <module>

    from requests.packages.urllib3.exceptions import InsecureRequestWarning

ImportError: No module named requests.packages.urllib3.exceptions
```

**Comment by SteveMcGrath** [comment]
can you please try to install the latest version?  2.1.6 is current (not 2.1)

**Comment by SteveMcGrath** [comment]
Closing from lack of response.
