### ISSUE TITLE
Having issues passing in strings to sc.login()

### ISSUE THREAD

**Issue by Electronickss** [SteveMcGrath/pySecurityCenter#35]
I'm having trouble passing in a pair of strings as the username, password combo. I am using variables I read in from a file so I do not have to store the password in the script. A snippet of my code:

```
sc = SecurityCenter5('fullyqualified.domain.name')
with open('/Users/<username>/security_center_automation/scManager.txt') as f:
	credentials=f.readlines()
	user = (credentials[0])
	passwd = (credentials[1])
	sc.login(user, passwd)
```

I am getting for an error:

> Traceback (most recent call last):
>   File "/Users/<username>/security_center_automation/importAssets.py", line 23, in <module>
>     sc.login(user, passwd)
>   File "/Library/Python/2.7/site-packages/securitycenter/sc5.py", line 44, in login
>     resp = self.post('token', json={'username': user, 'password': passwd})
>   File "/Library/Python/2.7/site-packages/securitycenter/base.py", line 91, in post
>     return self._resp_error_check(resp)
>   File "/Library/Python/2.7/site-packages/securitycenter/sc5.py", line 31, in _resp_error_check
>     raise APIError(d['error_code'], d['error_msg'])
> securitycenter.base.APIError: u'[161]: Invalid login credentials\n'
> [Finished in 1.0s with exit code 1]
> [shell_cmd: python -u "/Users/<username>/security_center_automation/importAssets.py"]
> [dir: /Users/<username>/security_center_automation]
> [path: /usr/bin:/bin:/usr/sbin:/sbin]

Edit: Security Center 5.3.2. And yes these credentials are correct and are of type string

**Comment by Electronickss** [comment]
Apologies, I didnt notice that I had a newline at the end of both my username and password. A simple .rstrip() took care of that

**Comment by Electronickss** [comment]
Thought I had closed it already
