### ISSUE TITLE
Trying to update existing assets

### ISSUE THREAD

**Issue by Electronickss** [SteveMcGrath/pySecurityCenter#36]
I am running into an issue trying to update assets that already exist. 

Using the sc.post() method I get:

```
Traceback (most recent call last):
  File "/Users/<username>/security_center_automation/importAssets.py", line 74, in <module>
    assetUpdateFunction(scan, str_asset_scan_list)
  File "/Users/<username>/security_center_automation/importAssets.py", line 35, in assetUpdateFunction
    'tags': name,
  File "/Library/Python/2.7/site-packages/securitycenter/base.py", line 91, in post
    return self._resp_error_check(resp)
  File "/Library/Python/2.7/site-packages/securitycenter/sc5.py", line 31, in _resp_error_check
    raise APIError(d['error_code'], d['error_msg'])
securitycenter.base.APIError: u"[144]: Adding Asset 'a' failed.\nAsset name already exists.\n"
[Finished in 1.3s with exit code 1]
[shell_cmd: python -u "/Users/<username>/security_center_automation/importAssets.py"]
[dir: /Users/<username>/security_center_automation]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
```

Which makes sense that sc.post() would give that result. Looking under the [nessus api documentation](https://support.tenable.com/support-center/cerberus-support-center/includes/widgets/sc_api/Asset.html) it looks like sc.post() needs to be able to create a new asset.

However it looks like sc.patch() should allow for editing of existing assets. and according to the documentation, it takes the same arguments as sc.post(). So I tried mostly the same parameters and recieved this error:

```
Traceback (most recent call last):
  File "/Users/<username>/security_center_automation/importAssets.py", line 75, in <module>
    assetPatchFunction(scan, str_asset_scan_list)
  File "/Users/<username>/security_center_automation/importAssets.py", line 49, in assetPatchFunction
    'tags': name,
  File "/Library/Python/2.7/site-packages/securitycenter/base.py", line 107, in patch
    return self._resp_error_check(resp)
  File "/Library/Python/2.7/site-packages/securitycenter/sc5.py", line 31, in _resp_error_check
    raise APIError(d['error_code'], d['error_msg'])
securitycenter.base.APIError: u'[11]: Resource does not support this method.'
[Finished in 1.0s with exit code 1]
[shell_cmd: python -u "/Users/<username>/security_center_automation/importAssets.py"]
[dir: /Users/<username>/security_center_automation]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
```

Is this a mistake on my part? Or has patch not been implemented as a feature?

**Comment by Electronickss** [comment]
Here is my current code
http://pastebin.com/Cwn8CfSP

We have two types of asset groups, those we use to define scans, the keys of the original json dictionary, and all of our customers within that set, which are used to group information.

**Comment by Electronickss** [comment]
After rereading through the `ips_in_asset_groups` example in sc5, I realized that I was not passing the id of the asset in with my patch request. I also noticed that I had `json={....}` in my request, which I had copied from the `csv_import` example in sc5. When I switched it to `params={...}` and passed in the the id of the asset I was trying to patch like this: `'asset/%s' % ident` where ident is the id of the asset group, I was able to solve my issue. 

My current functions look like this:
```
# Defining Asset Create Function
def assetCreateFunction(name, ip_list):
	sc.post('asset', params={
			'context': '',
			'createdTime': 0,
			'modifiedTime': 0,
			'canManage' : 'true',
			'type': 'static',
			'name': name,
			'definedIPs': ip_list,
			'description': name,
			'tags': name,
	}),


# Defining Asset Patch Function
def assetPatchFunction(name, ip_list, ident):
	sc.patch('asset/%s' % ident, params={
			'name': name,
			'definedIPs': ip_list,
	}),
```

This means I needed to configure a get request of the assets. I built the response into a dictionary of dictionaries.

I call those functions with a try catch block, that fires if there is a KeyError (if the variable doesn't exist from the get request) it will fire the create function
