### ISSUE TITLE
header value wrong type

### ISSUE THREAD

**Issue by neightd0g** [SteveMcGrath/pySecurityCenter#41]
I'm having trouble just getting started. Please advise.

$ cat sc5apitool
#!/usr/bin/env python
from securitycenter import SecurityCenter5
sc = SecurityCenter5('<FQDN>')
sc.login('<USER>','<PASS>')
response = sc.get('status')
print response

$ ./sc5apitool 
Traceback (most recent call last):
  File "./sc5apitool", line 7, in <module>
    response = sc.get('status')
  File "/home/ec2-user/sc5apitool/.venv/local/lib64/python2.7/site-packages/securitycenter/base.py", line 79, in get
    resp = self._session.get(self._url(path), **self._builder(**kwargs))
  File "/home/ec2-user/sc5apitool/.venv/local/lib/python2.7/site-packages/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/home/ec2-user/sc5apitool/.venv/local/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    prep = self.prepare_request(req)
  File "/home/ec2-user/sc5apitool/.venv/local/lib/python2.7/site-packages/requests/sessions.py", line 394, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/ec2-user/sc5apitool/.venv/local/lib/python2.7/site-packages/requests/models.py", line 295, in prepare
    self.prepare_headers(headers)
  File "/home/ec2-user/sc5apitool/.venv/local/lib/python2.7/site-packages/requests/models.py", line 409, in prepare_headers
    check_header_validity(header)
  File "/home/ec2-user/sc5apitool/.venv/local/lib/python2.7/site-packages/requests/utils.py", line 800, in check_header_validity
    "not %s" % (value, type(value)))
requests.exceptions.InvalidHeader: Header value 1913645890 must be of type str or bytes, not <type 'int'>

**Comment by SteveMcGrath** [comment]
Are you using the latest rev of the library?

**Comment by neightd0g** [comment]
pretty sure, yeah:

$ cat requirements.txt
pysecuritycenter==3.0

**Comment by SteveMcGrath** [comment]
you may want to update that to 3.0.2.  this issue was discovered and addressed in 3.0.1

**Comment by neightd0g** [comment]
Problem solved. Thank you!
