### ISSUE TITLE
Having an issue pulling data from vulndetails

### ISSUE THREAD

**Issue by jasntiamak** [SteveMcGrath/pySecurityCenter#58]
I am attempting to build some custom asset lists based on the vulntext of an audit file plugin.  Error below. Other calls execute fine.

Traceback (most recent call last):
  File "./asset_redux.py", line 7, in <module>
    response = sc.analysis(('pluginID', '=', '1006879'), tool='vulndetails')
  File "/usr/local/lib/python2.7/dist-packages/securitycenter/sc5.py", line 136, in analysis
    resp = self.post('analysis', json=kwargs)
  File "/usr/local/lib/python2.7/dist-packages/securitycenter/base.py", line 96, in post
    return self._resp_error_check(resp)
  File "/usr/local/lib/python2.7/dist-packages/securitycenter/sc5.py", line 31, in _resp_error_check
    raise APIError(d['error_code'], d['error_msg'])
securitycenter.base.APIError: u'[143]: Unable to process Vuln Query.\nSecurityCenter could not process the vulnerability filter string (SC_ROOT=/opt/sc /opt/sc/bin/showvulns  +orgid "1" +groupid "0" +tool \'vulndetails\' +sourcetype \'cumulative\' +startoffset \'0\' +endoffset \'1000\' +pluginid \'1006879\' +repository "15,16,18,22,23,24,25,26"  -acceptRisk).\nNo response from showvulns\n'

**Comment by SteveMcGrath** [comment]
please test with pyTenable and re-open over there if still an issue.
